export default
{
    "_id": {
        "$oid": "5c8dc7c0b6aa482b6f8ac885"
    },
    "cards": [
        "______: good to the last drop.",
        "______: kid tested, mother approved.",
        "______: kid-tested, mother-approved.",
        "______: Once you pop, the fun don't stop!",
        "______? Jim'll fix it!",
        "______? There's an app for that.",
        "______? Yeah, nah.",
        "______. Awesome in theory, kind of a mess in practice.",
        "______. Betcha can't have just one!",
        "______. High five, bro.",
        "______. It's a trap!",
        "______. That was so metal.",
        "______. That's how I want to die.",
        "______. That's why mums go to Iceland.",
        "★✰✰✰✰ Do NOT go here! Found _____ in my Kung Pao chicken!",
        "50% of all marriages end in ______.",
        "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ______.",
        "A remarkable new study has shown that chimps have evolved their own primitive version of ______.",
        "A romantic candlelit dinner would be incomplete without ______.",
        "A romantic, candlelit dinner would be incomplete without ______.",
        "A successful job interview begins with a firm handshake and ends with ______.",
        "After eight years in the White House, how is Obama finally letting loose?",
        "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ______.",
        "After Hurricane Katrina, Sean Penn brought ______ to all the people of New Orleans.",
        "After Hurricane Katrina, Sean Penn brought ______ to the people of New Orleans.",
        "After the earthquake, Sean Penn brought ______ to the people of Haiti.",
        "Air Canada guidelines now prohibit ______ on airplanes.",
        "Airport security guidelines now prohibit ______ on airplanes.",
        "Alternative medicine is now embracing the curative powers of ______.",
        "And the BAFTA for ______ goes to ______.",
        "And what did you bring for show and tell?",
        "Anthropologists have recently discovered a primitive tribe that worships ______.",
        "Arby's: We Have ______.",
        "\"Are you thinking what I'm thinking, B1?",
        "",
        "I think I am, B2: it's ______ time!\"",
        "As my New Year's resolution, I vow to give up ______.",
        "As the mom of five rambunctious boys, I'm no stranger to ______.",
        "As the mum of five rambunctious boys, I'm no stranger to ______.",
        "Betcha can't have just one!",
        "BILLY MAYS HERE FOR ______.",
        "Bravo's new reality show features eight washed-up celebrities living with ______.",
        "Brought to you by Bud Light®, the Official Beer of ______.",
        "Brought to you by Molson Canadian, the Official Beer of ______.",
        "Brought to you by XXXX Gold, the Official Beer of ______.",
        "But before I kill you, Mr. Bond, I must show you ______.",
        "CBC presents \"___: the Story of ___.\"",
        "Channel 4 presents ______, the story of ______.",
        "Channel 5's new reality show features eight washed-up celebrities living with ______.",
        "Channel 9 is pleased to present its new variety show, \"Hey Hey It's ______.\"",
        "Charades was ruined for me forever when my mom had to act out ______.",
        "Check me out, yo! I call this dance move \"______.\"",
        "Click Here for ______!!!",
        "Coming this season, Samuel Beckett's classic existential play: Waiting for ______.",
        "Coming to Broadway this season, ______: The Musical.",
        "Coming to the West End this year, ______: The Musical.",
        "Crikey! I've never seen ______ like this before! Let's get a bit closer.",
        "Daddy, why is mommy crying?",
        "Daddy, why is mummy crying?",
        "Dear Abby, I'm having some trouble with ______ and would like your advice.",
        "Dear Agony Aunt, I'm having some trouble with ________ and I need your advice.",
        "Doctor, you've gone too far! The human body wasn't meant to withstand that amount of ______!",
        "Dude, do not go in that bathroom. There's ______ in there.",
        "Dude, do not go in that washroom. There's ______ in there.",
        "Due to a PR fiasco, Walmart no longer offers ______.",
        "During his childhood, Salvador Dali produced hundreds of paintings of ______.",
        "During his midlife crisis, my dad got really into ______.",
        "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ______.",
        "During sex, I like to think about ______.",
        "Finally! A service that delivers ______ right to your door.",
        "Fun tip! When your man asks you to go down on him, try surprising him with ______ instead.",
        "Future historians will agree that ______ marked the beginning of America's decline.",
        "\"Here is the church",
        "Here is the steeple",
        "Open the doors",
        "And there is ______.\"",
        "Hey guys, welcome to Boston Pizza! Would you like to start the night off right with ______?",
        "Hey guys, welcome to Chili's! Would you like to start the night off right with ______?",
        "Hey guys, welcome to Sizzler! Would you like to start the night off right with ______?",
        "Hey guys, welcome to TGIF! Would you like to start the night off right with ______?",
        "Hey Reddit! I'm ______. Ask me anything.",
        "How am I maintaining my relationship status?",
        "How did I lose my virginity?",
        "I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.",
        "I drink to forget ______.",
        "I get by with a little help from ______.",
        "I got 99 problems but ______ ain't one.",
        "I know when that hotline bling, that can only mean one thing: ______.",
        "I learned the hard way that you can't cheer up a grieving friend with ______.",
        "I wish I hadn't lost the instruction manual for ______.",
        "I'm going on a cleanse this week. Nothing but kale juice and ______.",
        "I'm Lebron James, and when I'm not slamming dunks, I love ______.",
        "I'm no doctor, but I'm pretty sure what you're suffering from is called \"______.\"",
        "I'm sorry, Professor, but I couldn't complete my homework because of ______.",
        "I'm sorry, Sir, but I couldn't complete my homework because of ______.",
        "I\u2019m not like the rest of you. I\u2019m too rich and busy for ______.",
        "If you can't be with the one you love, love ______.",
        "IF you like ______, YOU MIGHT BE A REDNECK.",
        "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
        "In 1,000 years, when paper money is but a distant memory, ______ will be our currency.",
        "In an attempt to reach a wider audience, the National Museum of Australia has opened an interactive exhibit on ______.",
        "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ______.",
        "In Australia, ______ is twice as big and twice as deadly.",
        "In Belmarsh Prison, word is you can trade 200 cigarettes for ______.",
        "In her latest feature-length film, Tracy Beaker struggles with ______ for the first time.",
        "In his new self-produced album, Kanye West raps over the sounds of ______.",
        "In L.A. County Jail, word is you can trade 200 cigarettes for ______.",
        "In Michael Jackson's final moments, he thought about ______.",
        "In Rome, there are whisperings that the Vatican has a secret room devoted to ______.",
        "In the new Disney Channel Original Movie, Hannah Montana struggles with ______ for the first time.",
        "In the seventh circle of Hell, sinners must endure ______ for all eternity.",
        "In Wormwood Scrubs, word is you can trade 200 cigarettes for ______.",
        "Instead of coal, Father Christmas now gives the bad children ______.",
        "Instead of coal, Santa now gives the bad children ______.",
        "Introducing X-Treme Baseball! It's like baseball, but with ______!",
        "It's a trap!",
        "It\u2019s a pity that kids these days are all getting involved with ______.",
        "Just once, I'd like to hear you say \"Thanks, Mom. Thanks for ______.\"",
        "Just once, I'd like to hear you say \"Thanks, Mum. Thanks for ______.\"",
        "Just saw this upsetting video! Please retweet!! #stop______",
        "Kids, I don't need drugs to get high. I'm high on ______.",
        "Life for Aboriginal people was forever changed when the white man introduced them to ______.",
        "Life for American Indians was forever changed when the White Man introduced them to ______.",
        "Life was difficult for cavemen before ______.",
        "Lovin\u2019 you is easy \u2019cause you\u2019re ______.",
        "Major League Baseball has banned ______ for giving players an unfair advantage.",
        "Mate, do not go in that bathroom. There's ______ in there.",
        "Mate, do not go in that toilet. There's ______ in there.",
        "Maybe she's born with it. Maybe it's ______.",
        "Men's Wearhouse: You're gonna like ______. I guarantee it.",
        "Military historians remember Alexander the Great for his brilliant use of ______ against the Persians.",
        "Money can\u2019t buy me love, but it can buy me ______.",
        "Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is ______?",
        "MTV's new reality show features eight washed-up celebrities living with ______.",
        "My fellow Americans: Before this decade is out, we will have ______ on the moon!",
        "Next from J.K. Rowling: Harry Potter and the Chamber of ______.",
        "Next from J.K. Rowling: Harry Potter and the Chamber of ______.",
        "Next on ESPN2: The World Series of ______.",
        "Next on Eurosport: The World Championship of _______.",
        "Next on Nine's Wide World of Sports: The World Championship of ______.",
        "Next on Sky Sports: The World Championship of ________.",
        "Next on Sky Sports: The World Champsion of ________.",
        "Next on TSN: The World Series of ______.",
        "Next up on Channel 4: Ramsay's ______ Nightmares.",
        "Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ________.",
        "Now at the National Museum of Australia: an interactive exhibit on ______.",
        "Now at the Natural History Museum: an interactive exhibit on ______.",
        "Now at the Royal Ontario Museum: an interactive exhibit on ______.",
        "Now at the Smithsonian: an interactive exhibit on ______.",
        "O Canada, we stand on guard for ______.",
        "Oi! Show us ______!",
        "Old MacDonald had ______. E-I-E-I-O.",
        "Only two things in life are certain: death and ______.",
        "Penalty! ______: that's 5 minutes in the box!",
        "Qantas now prohibits ______ on airplanes.",
        "Science will never explain ______.",
        "Skidamarink a dink a dink, skidamarink a doo, I love ______.",
        "Sorry everyone, I just ______.",
        "Studies show that lab rats navigate mazes 50% faster after being exposed to ______.",
        "TFL apologizes for the delay in train service due to ______.",
        "The blind date was going horribly until we discovered our shared interest in ______.",
        "The class field trip was completely ruined by ______.",
        "The Five Stages of Grief: denial, anger, bargaining, ______, acceptance.",
        "The healing process began when I joined a support group for victims of ______.",
        "The Natural History Museum has just opened an interactive exhibit on ________.",
        "The new Chevy Tahoe. With the power and space to take ______ everywhere you go.",
        "The school excursion was completely ruined by ______.",
        "The school field trip was completely ruined by ______.",
        "The school trip was completely ruined by ______.",
        "The secret to a lasting marriage is communication, communication, and ______.",
        "The Smithsonian Museum of Natural History has just opened an interactive exhibit on ______.",
        "The TFL apologizes for the delay in train service due to ________. ",
        "The theme for next year's Eurovision Song Contest is \"We are ________.\"",
        "The U.S. has begun airdropping ______ to the children of Afghanistan.",
        "\"This is the way the world ends",
        "This is the way the world ends",
        "Not with a bang but with ______.\"",
        "This is your captain speaking. Fasten your seatbelts and prepare for ______.",
        "This season at Steppenwolf, Samuel Beckett's classic existential play: Waitng for ______.",
        "This season at the old Vic, Samuel Beckett's classic existential play: Waitng for ______.",
        "This season at the Princess of Wales Theatre, Samuel Beckett's classic existential play: Waiting for ______.",
        "This season at the Sydney Opera House, Samuel Beckett's classic existential play: Waiting for ______.",
        "Today on Jerry Springer: \"Help! My son is ______!\"",
        "Today on Maury: \"Help! My son is ______!\"",
        "Today on The Jeremy Kyle Show: \"Help! My son is ________!\"",
        "Tonight's top story: What you don't know about ________ could kill you.",
        "TSA guidelines now prohibit ______ on airplanes.",
        "Turns out that ______-Man was neither the hero we needed nor wanted.",
        "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ______.",
        "UKIP: Putting ______ First!",
        "War! What is it good for?",
        "Well if you'll excuse me, gentlemen, I have a date with ______.",
        "What am I giving up for Lent?",
        "What are my parents hiding from me?",
        "What are school administrators using to curb rampant teenage pregnancy?",
        "What broke up the original Wiggles?",
        "What brought the orgy to a grinding halt?",
        "What did I bring back from Amsterdam?",
        "What did I bring back from Bali?",
        "What did I bring back from Mexico?",
        "What did the US airdrop to the children of Afghanistan?",
        "What did Vin Diesel eat for dinner?",
        "What do old people smell like?",
        "What does Dick Cheney prefer?",
        "What don't you want to find in your Chinese food?",
        "What don't you want to find in your doner kebab?",
        "What don't you want to find in your Kung Pao chicken?",
        "What don't you want to find in your Mongolian beef?",
        "What ended my last relationship?",
        "What gets better with age?",
        "What gives me uncontrollable gas?",
        "What has been making life difficult at the nudist colony?",
        "What helps Barack Obama unwind?",
        "What helps Obama unwind?",
        "What is Batman's guilty pleasure?",
        "What is George W. Bush thinking about right now?",
        "What kept Margaret Thatcher busy in her waning years?",
        "What left this stain on my couch?",
        "What made my first kiss so awkward?",
        "What makes life worth living?",
        "What makes me a true blue Aussie?",
        "What never fails to liven up the party?",
        "What will always get you laid?",
        "What will I bring back in time to convince people that I am a powerful wizard?",
        "What would grandma find disturbing, yet oddly charming?",
        "What's a girl's best friend?",
        "What's my anti-drug?",
        "What's my secret power?",
        "What's Teach for America using to inspire inner city students to succeed?",
        "What's that smell?",
        "What's that sound?",
        "What's the Canadian government using to inspire rural students to succeed?",
        "What's the crustiest?",
        "What's the most emo?",
        "What's the new fad diet?",
        "What's the next Happy Meal® toy?",
        "What's there a ton of in heaven?",
        "What's there a tonne of in heaven?",
        "When all else fails, I can always masturbate to ______.",
        "When I am a billionare, I shall erect a 20-meter statue to commemorate ______.",
        "When I am a billionare, I shall erect a 20-metre statue to commemorate ______.",
        "When I am a billionare, I shall erect a 50-foot statue to commemorate ______.",
        "When I am President of the United States, I will create the Department of ______.",
        "When I am President, I will create the Department of ______.",
        "When I am Prime Minister of Canada, I will create the Department of ______.",
        "When I am Prime Minister of Canada, I will create the Ministry of ______.",
        "When I am Prime Minister of the United Kingdom, I will create the Ministry of ______.",
        "When I am Prime Minister, I will create the Department of ______.",
        "When I am Prime Minister, I will create the Ministry of ______.",
        "When I pooped, what came out of my butt?",
        "When I'm in prison, I'll have ______ smuggled in.",
        "When Pharaoh remained unmoved, Moses called down a Plague of ______.",
        "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ______.",
        "White people like ______.",
        "Who stole the cookies from the cookie jar?",
        "Why am I sticky?",
        "Why can't I sleep at night?",
        "Why do I hurt all over?",
        "Your persistence is admirable, my dear Prince. But you cannot win my heart with ______ alone.",
        ""
    ],
    "ownerId": {
        "$oid": "5c8a02a89f0f3cbb9a5b75f6"
    },
    "__v": 0
}